-- Create the rsvp table
CREATE TABLE rsvp (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  name TEXT NOT NULL,
  nik TEXT NOT NULL,
  attendance BOOLEAN DEFAULT TRUE
);

-- Set up Row Level Security (RLS)
-- Enable RLS
ALTER TABLE rsvp ENABLE ROW LEVEL SECURITY;

-- Allow anonymous inserts (since this is a public invitation)
CREATE POLICY "Allow anonymous inserts" ON rsvp FOR INSERT WITH CHECK (true);

-- Allow anonymous reads (optional, if you want to show a guest list)
-- CREATE POLICY "Allow anonymous reads" ON rsvp FOR SELECT USING (true);
